#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : intltool
Version  : 0.51.0
Release  : 11
URL      : https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
Source0  : https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: intltool-bin
Requires: intltool-data
Requires: intltool-doc
BuildRequires : perl(XML::Parser)

%description
===============
these at http://bugs.launchpad.net/intltool on Launchpad. Patches are
also very welcome. See HACKING for more information on submitting patches.

%package bin
Summary: bin components for the intltool package.
Group: Binaries
Requires: intltool-data

%description bin
bin components for the intltool package.


%package data
Summary: data components for the intltool package.
Group: Data

%description data
data components for the intltool package.


%package dev
Summary: dev components for the intltool package.
Group: Development
Requires: intltool-bin
Requires: intltool-data

%description dev
dev components for the intltool package.


%package doc
Summary: doc components for the intltool package.
Group: Documentation

%description doc
doc components for the intltool package.


%prep
%setup -q -n intltool-0.51.0

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/intltool-extract
/usr/bin/intltool-merge
/usr/bin/intltool-prepare
/usr/bin/intltool-update
/usr/bin/intltoolize

%files data
%defattr(-,root,root,-)
/usr/share/intltool/Makefile.in.in

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
